### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by abbyreyna** [zcsocal/groupproject#2]
## User Story:
A hiker with asthma is looking for a nearby trail with the best air quality conditions.

## Acceptance Criteria
- [x] index.html has a text input
- [x] index.html has a search button

1. User has to give location, either by agreeing to share location with website or by entering their location

**Comment by be04zimm** [comment]
- [x] Add javascript that links to the search button.
- [x] Need div to hold user input
- [x] Need array of trail addresses
- [x] Calculate distance from user location to trail address
- [x] Populate top 10 trails, based on closest distance
